In [1]:
from google.colab import files
uploaded=files.upload()

Saving heart.csv to heart.csv

In [3]:
#Load Dataset
import pandas as pd
df = pd.read_csv("heart.csv")

In [4]:
#inspect dataset Shape
df.shape

(1025, 14)

In [5]:
df.dtypes #checking column types

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [6]:
#viewing first five rows
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [7]:
data_dictionary = {
    "age": "Age of the patient in years",
    "sex": "Gender (1=Male, 0=Female)",
    "cp": "Chest Pain Type (0=Typical Angina, 1=Atypical Angina, 2=Non-anginal Pain, 3=Asymptomatic)",
    "trestbps": "Resting Blood Pressure (mm Hg)",
    "chol": "Serum Cholesterol (mg/dL)",
    "fbs": "Fasting Blood Sugar > 120 mg/dL (1=True, 0=False)",
    "restecg": "Resting ECG Results (0=Normal, 1=ST-T Abnormality, 2=Left Ventricular Hypertrophy)",
    "thalach": "Maximum Heart Rate Achieved",
    "exang": "Exercise-Induced Angina (1=Yes, 0=No)",
    "oldpeak": "ST Depression Induced by Exercise Relative to Rest",
    "slope": "Slope of Peak Exercise ST Segment (0=Upsloping, 1=Flat, 2=Downsloping)",
    "ca": "Number of Major Vessels Colored by Fluoroscopy",
    "thal": "Thalassemia Status (1=Normal, 2=Fixed Defect, 3=Reversible Defect)",
    "target": "Heart Disease Presence (1=Disease, 0=No Disease)"
}

for column, meaning in data_dictionary.items():
    print(f"{column}: {meaning}")

age: Age of the patient in years
sex: Gender (1=Male, 0=Female)
cp: Chest Pain Type (0=Typical Angina, 1=Atypical Angina, 2=Non-anginal Pain, 3=Asymptomatic)
trestbps: Resting Blood Pressure (mm Hg)
chol: Serum Cholesterol (mg/dL)
fbs: Fasting Blood Sugar > 120 mg/dL (1=True, 0=False)
restecg: Resting ECG Results (0=Normal, 1=ST-T Abnormality, 2=Left Ventricular Hypertrophy)
thalach: Maximum Heart Rate Achieved
exang: Exercise-Induced Angina (1=Yes, 0=No)
oldpeak: ST Depression Induced by Exercise Relative to Rest
slope: Slope of Peak Exercise ST Segment (0=Upsloping, 1=Flat, 2=Downsloping)
ca: Number of Major Vessels Colored by Fluoroscopy
thal: Thalassemia Status (1=Normal, 2=Fixed Defect, 3=Reversible Defect)
target: Heart Disease Presence (1=Disease, 0=No Disease)